  image_size: 1024


  image_encoder: "sam_vit_b_adapter"
  mask_decoder: "lora_mask_decoder"
  sam_checkpoint: "weights/sam_vit_b.pth"


  wandb_project_name: "ACDC"

  dataset:
    name: acdc
    root: /dataNfs/ncp/SamRadiology-main/dataset/acdc
    image_size: 1024
    split: 0.0526 # 0.0263 # training split
    seed: 42
    batch_size: 4
    num_workers: 4
    num_classes: 3
    num_tokens: 10

  training:
    max_epochs: 200
    save_path: checkpoints/ACDC

  inference:
    name: acdc_test
    root: /path/to/your/test_data
    checkpoint_path: /path/to/your/checkpoint