image_size: 1024
image_encoder: "sam_vit_b_adapter"
mask_decoder: "lora_mask_decoder"
sam_checkpoint: "weights/sam_vit_b.pth"
wandb_project_name: "isic2016"
prompt_predictor: "sam_vitb_high_res_ppn"

dataset:
  name: isic2016
  root: /dataNfs/ncp/SamRadiology-main/dataset/ISIC2016
  image_size: 512
  split: 0.88
  seed: 42
  batch_size: 8
  num_workers: 4
  num_classes: 1
  num_tokens: 10

training:
  max_epochs: 500
  save_path: checkpoints/isic2016

inference:
  name: isic2016_test
  root: /dataNfs/ncp/SamRadiology-main/tn3k/test
  checkpoint_path: checkpoints/tn3k/XXX.pt