
image_size: 1024
image_encoder: "sam_vit_b_adapter"
mask_decoder: "lora_mask_decoder"
sam_checkpoint: "weights/sam_vit_b.pth"
wandb_project_name: "isic2016"
prompt_predictor: "sam_vitb_high_res_ppn"

inference:
  model_checkpoint: "checkpoints/model_epoch=499-val_dice=0.95-v1.ckpt"
  input_images: /dataNfs/ncp/SamRadiology-main/dataset/ISIC2016
  output_dir: /dataNfs/ncp/SamRadiology-main/logs/result/dataset/ISIC2016
  image_size: 512
  name: isic2016_test

dataset:
  name: isic2016
  root: /dataNfs/ncp/SamRadiology-main/dataset/ISIC2016
  image_size: 512
  split: 0.75
  seed: 42
  batch_size: 4
  num_workers: 4
  num_classes: 1
  num_tokens: 10