
image_size: 1024
image_encoder: "sam_vit_b_adapter"
mask_decoder: "lora_mask_decoder"
sam_checkpoint: "weights/sam_vit_b.pth"
wandb_project_name: "tn3k"
prompt_predictor: "sam_vitb_high_res_ppn"

inference:
  model_checkpoint: "checkpoints/model_epoch=399-val_dice=0.95.ckpt"
  input_images: /dataNfs/ncp/SamRadiology-main/dataset/Synapse
  output_dir: /dataNfs/ncp/SamRadiology-main/logs/result/synapse
  image_size: 512
  name: synapse_test

dataset:
  name: synapse
  root: /dataNfs/ncp/SamRadiology-main/dataset/Synapse
  image_size: 512
  split: 0.8 # 0.0263 # training split
  seed: 42
  batch_size: 4
  num_workers: 4
  num_classes: 7
  num_tokens: 10